export const enum APP {
  SET_LANGUAGE = 'APP/SET_LANGUAGE',
  SET_THEME = 'APP/SET_THEME',
  SET_AUTHENTICATED = 'APP/SET_AUTH',
  SET_NETWORK_STATUS = 'APP/SET_NETWORK_STATUS',
}

export const enum AUTH {
  SET_STATE = 'AUTH/SET_STATE',
  CLEAR_STATE = 'AUTH/CLEAR_STATE',
}

// eslint-disable-next-line @typescript-eslint/naming-convention
export const enum BACKGROUND_TASKS {
  SET_STATE = 'BACKGROUND_TASKS/SET_STATE',
}

export const enum DEVICES {
  SET_STATE = 'DEVICES/SET_STATE',
  SET_CONFIG = 'DEVICES/SET_CONFIGURATION',
}

export const enum ENUMS {
  SET_STATE = 'ENUMS/SET_STATE',
}

export const enum MODAL {
  OPEN = 'MODAL/OPEN',
  CLOSE = 'MODAL/CLOSE',
}

export const enum VIDEOS {
  SET_STATE = 'VIDEOS/SET_STATE',
}

export const enum WARNING {
  SET_SNACKBAR_MESSAGES = 'WARNING/SET_SNACKBAR_MESSAGES',
  // ALERT = 'WARNING/ALERT',
  // HIDE_ALERT = 'WARNING/HIDE_ALERT',

  SET_IS_SAVING_DATA = 'WARNING/LOADING/SET_IS_SAVING_DATA',
  SET_IS_LOADING_DATA = 'WARNING/LOADING/SET_IS_LOADING_DATA',
  SET_IS_DELETING_DATA = 'WARNING/LOADING/SET_IS_DELETING_DATA',
  SET_IS_UPLOADING_FILE = 'WARNING/LOADING/SET_IS_UPLOADING_FILE',
}
